//USER
export const USER_FETCH_PENDING = 'USER_FETCH_PENDING';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_FETCH_ERROR = 'USER_FETCH_ERROR';
export const USER_LOGOFF = 'USER_LOGOFF';
//FAQ
export const FAQ_FETCH_PENDING = 'FAQ_FETCH_PENDING';
export const FAQ_FETCH_SUCCESS = 'FAQ_FETCH_SUCCESS';
export const FAQ_FETCH_ERROR = 'FAQ_FETCH_ERROR';
