export const USER_FETCH_PENDING = 'USER_FETCH_PENDING';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_FETCH_ERROR = 'USER_FETCH_ERROR';
export const USER_LOGOFF = 'USER_LOGOFF';
export const USER_SAVEPREFERENCES_PENDING = 'USER_SAVEPREFERENCES_PENDING';
export const USER_SAVEPREFERENCES_SUCCESS = 'USER_SAVEPREFERENCES_SUCCESS';
export const USER_SAVEPREFERENCES_ERROR = 'USER_SAVEPREFERENCES_ERROR';
